filesystem:
  endpoint: 
  bucket: 
aws:
  access_key: 
  secret_access_key: 
  session_token: 
  default_region: 
llm:
  api_key:
input:
  input_dir:
  input_file:
  input_variables:
output:
  output_dir: 