filesystem:
  endpoint: 
  bucket: 
aws:
  access_key: 
  secret_access_key: 
  session_token: 
  default_region: 
llm:
  method:
  prompt:
    model:
    api_key:
    url:
  embedding:
    model:
    dim: 
requests:
  timeout: 5 # In seconds 
  default_language: English
input:
  input_dir: input
  input_file:
  input_variables:
output:
  output_dir: output
seed: 