filesystem:
  endpoint: 
  bucket: 
aws:
  access_key: 
  secret_access_key: 
  session_token: 
  default_region: 
llm:
  method:
  embedding:
    dim: 
  api_key:
  model: 
  base_url: 
requests:
  timeout: 5
  default_language: English
input:
  input_dir: input
  input_file:
  input_variables:
output:
  output_dir: output